# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='update_time',
        ),
        migrations.AddField(
            model_name='detail',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
