# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170912_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
