# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20170914_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_time',
            field=models.CharField(max_length=30),
        ),
    ]
