# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20170914_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_time',
            field=models.DateTimeField(max_length=30),
        ),
    ]
