# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20170914_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
