# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20170915_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_time',
            field=models.DateField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
