# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20170919_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='core_version',
            new_name='coreversion',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='web_version',
            new_name='webversion',
        ),
    ]
