# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20170919_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='remark',
            new_name='remarks',
        ),
    ]
